# Generated by Django 4.1.13 on 2024-11-11 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_feature_rentalunit_rentalunitfeature_rentallimit'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalunit',
            name='features',
            field=models.ManyToManyField(related_name='rental_units', through='api.RentalUnitFeature', to='api.feature'),
        ),
    ]
