# Generated by Django 4.1.13 on 2024-11-11 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rentalunit_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalunit',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
